### PR TITLE
Add cassandra column family cache metrics.

### PR DESCRIPTION
**Pull request by plathrop**

### CODE REVIEW

**Comment by motivator** [comment]
does it make sense to get_local_ipv4() so many times or would it make more sense to do that at instance install time and store the data locally for use by anything running locally?

**Comment by plathrop** [comment]
Though on second thought, when/if that happens, the processes themselves are
gonna have trouble too, since they bind to a specific IP...

Maybe I should just do a single call during the run of the metrics?

**Comment by plathrop** [comment]
The IP can change. It usually doesn't, but that behavior is not guaranteed.

**Comment by motivator** [comment]
i assume the ip cannot change while and instance is running, though. in that case why not get the local ip once on startup?

**Comment by plathrop** [comment]
Why not? It's DHCP.

**Pull request closed without merging**
